# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtWidgets
from threading import Thread

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(244, 152)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 222, 61))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.btn_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 1, 1, 1, 1)

        self.btn_guide = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_guide.setObjectName("btn_guide")
        self.gridLayout.addWidget(self.btn_guide, 0, 0, 1, 2)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)

        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 244, 21))
        self.menubar.setObjectName("menubar")

        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")

        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")

        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menu.addSeparator()

        self.menubar.addAction(self.menu.menuAction())

        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.btn_start.setText(_translate("MainWindow", "Старт"))

        self.btn_guide.setText(_translate("MainWindow", "Руководство к использованию"))

        self.comboBox.setItemText(0, _translate("MainWindow", "Выберите моба..."))
        self.comboBox.setItemText(1, _translate("MainWindow", "Крэтс [1]"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Бешеный пёс [2]"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Огненная паучиха [3]"))
        self.menu.setTitle(_translate("MainWindow", "Мобы"))
        self.menu_2.setTitle(_translate("MainWindow", "Добыча"))

    def add_functions(self):
        self.btn_start.clicked.connect(self.btn_cl_start)
        self.btn_guide.clicked.connect(self.btn_cl_guide)


    def btn_cl_start(self):
        _translate = QtCore.QCoreApplication.translate

        if(self.comboBox.currentIndex() == 0):
            mob = '0'
            error_mob()
        elif (self.comboBox.currentIndex() == 1):
            mob = 'Crats'
        elif (self.comboBox.currentIndex() == 2):
            mob = 'Angry_Dog'
        elif (self.comboBox.currentIndex() == 3):
            mob = 'Fire_Spider'

        if mob != '0':
            if self.btn_start.text() == 'Старт':
                self.btn_start.setText(_translate("MainWindow", "Бот запущен."))
                th = Thread(target=click_start, args=([mob]), daemon=True)
                th.start()

    def btn_cl_guide(self):
        click_guide()







































if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

